# Generated by Django 4.2.7 on 2025-03-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingApp', '0002_user_aadhar_number_user_date_of_birth_user_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party_leader',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_pictures/'),
        ),
    ]
