# Generated by Django 4.2.7 on 2025-03-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingApp', '0003_candidate_party_candidate_party_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
