# Generated by Django 4.2.7 on 2025-04-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VotingApp', '0004_candidate_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='Constituencies',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
